Video: Switch to stock blender
blender-hip is no longer available,

error: blender-hip has been removed in favor of setting `config.rocmSupport = true` or using `pkgsRocm.blender`